/**
 * Frontmatter generation (Claude-only) and fast review.
 */

import { editor, select } from '@inquirer/prompts'
import matter from 'gray-matter'
import {
  ROLES, WORK_TYPES, FORMATS, DOMAINS, AUDIENCES, COMPLEXITIES, ERAS,
  type Role, type WorkType, type Frontmatter,
  type CorpusEntry,
  parseJsonResponse, scanCorpus,
} from './shared.js'

// ─── Claude Generation ──────────────────────────────────────────────────────

const FRONTMATTER_PROMPT = `You are a knowledge librarian. Given the document content below, generate YAML frontmatter metadata.

Return ONLY a JSON object (no markdown fences, no explanation) with these fields:
- title: string — human-readable document title
- role: one of [${ROLES.join(', ')}] — the document's relationship to knowledge
- format: one of [${FORMATS.join(', ')}] — the literary/structural form
- domain: one of [${DOMAINS.join(', ')}] — primary tradition or discipline
- tags: string[] — 3-7 topical keywords, lowercase, hyphenated
- audience: string[] — from [${AUDIENCES.join(', ')}]
- complexity: one of [${COMPLEXITIES.join(', ')}]
- summary: string — 1-3 sentence abstract
- source: one of [original, public-domain] or a URL/citation
- author: string — original author(s), if attributable (omit if unknown or collective/anonymous)
- origin_date: string — approximate date of creation (e.g., "~400 BCE", "1923", "13th century")
- era: one of [${ERAS.join(', ')}] — historical period
- tradition: string — specific lineage or school (e.g., "theravada", "zen", "sufi", "pragmatism"), omit if not applicable
- gaps_served: string — what gap in a knowledge corpus this document fills (1 sentence)
- graph_impact: string — what connections or conversations this document enables (1 sentence)

Document content:
`

export type GenerationResult = {
  provider: string
  suggestions: Partial<Frontmatter>
  /** Curation log fields — generated by Claude, not stored in frontmatter */
  curationMeta?: { gaps_served?: string; graph_impact?: string }
}

export async function generateFrontmatter(
  content: string,
  presets: { role?: string; domain?: string },
): Promise<GenerationResult> {
  const apiKey = process.env.ANTHROPIC_API_KEY

  if (apiKey) {
    try {
      const { default: Anthropic } = await import('@anthropic-ai/sdk')
      const client = new Anthropic({ apiKey })
      const truncated = content.slice(0, 6000)

      const message = await client.messages.create({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1024,
        messages: [{ role: 'user', content: FRONTMATTER_PROMPT + truncated }],
      })

      const textBlock = message.content.find((b) => b.type === 'text')
      if (textBlock && textBlock.type === 'text') {
        const parsed = parseJsonResponse(textBlock.text)
        if (parsed) {
          // Extract curation log fields before cleaning suggestions
          const curationMeta = {
            gaps_served: (parsed as Record<string, unknown>).gaps_served as string | undefined,
            graph_impact: (parsed as Record<string, unknown>).graph_impact as string | undefined,
          }
          delete (parsed as Record<string, unknown>).gaps_served
          delete (parsed as Record<string, unknown>).graph_impact

          const suggestions = applyPresets(parsed, presets)
          return { provider: 'Claude API', suggestions, curationMeta }
        }
      }
    } catch {
      // Fall through to manual
    }
  }

  return { provider: 'manual', suggestions: applyPresets({}, presets) }
}

function applyPresets(
  suggestions: Partial<Frontmatter>,
  presets: { role?: string; domain?: string },
): Partial<Frontmatter> {
  if (presets.role && ROLES.includes(presets.role as Role)) suggestions.role = presets.role as Role
  if (presets.domain) suggestions.domain = presets.domain
  return suggestions
}

// ─── Review ─────────────────────────────────────────────────────────────────

export async function reviewFrontmatter(
  suggestions: Partial<Frontmatter>,
  options: { accept?: boolean },
): Promise<Frontmatter> {
  const today = new Date().toISOString().slice(0, 10)

  const role: Role = (suggestions.role as Role) || 'source'
  const defaults: Frontmatter = {
    title: suggestions.title || '',
    role,
    work_type: suggestions.work_type || workTypeForRole(role),
    format: suggestions.format || 'essay',
    domain: suggestions.domain || 'philosophy',
    tags: suggestions.tags || [],
    audience: suggestions.audience || ['general'],
    complexity: suggestions.complexity || 'foundational',
    summary: suggestions.summary || '',
    curated_at: today,
    curator: suggestions.curator || 'shalom',
    source: suggestions.source || 'original',
    ...(suggestions.author && { author: suggestions.author }),
    ...(suggestions.origin_date && { origin_date: suggestions.origin_date }),
    ...(suggestions.era && { era: suggestions.era }),
    ...(suggestions.tradition && { tradition: suggestions.tradition }),
    ...(suggestions.related_docs && { related_docs: suggestions.related_docs }),
    ...(suggestions.parent_work && { parent_work: suggestions.parent_work }),
  }

  // Pretty-print suggestions
  console.log('\n── Frontmatter ─────────────────────────────────────')
  console.log(formatFrontmatter(defaults))
  console.log('────────────────────────────────────────────────────\n')

  if (options.accept) {
    console.log('✅ Auto-accepted (--accept)')
    return defaults
  }

  const action = await select({
    message: 'Review:',
    choices: [
      { name: 'Accept all', value: 'accept' },
      { name: 'Edit in $EDITOR', value: 'edit' },
      { name: 'Cancel', value: 'cancel' },
    ],
  })

  if (action === 'cancel') {
    console.log('Cancelled.')
    process.exit(0)
  }

  if (action === 'accept') {
    return defaults
  }

  // Edit mode: open frontmatter as YAML in editor
  const yaml = formatFrontmatter(defaults)
  const edited = await editor({
    message: 'Edit frontmatter (save and close to continue):',
    default: yaml,
    postfix: '.yaml',
  })

  return parseFrontmatterYaml(edited, defaults)
}

function workTypeForRole(role: Role): WorkType {
  if (role === 'collection') return 'collection'
  if (role === 'reference') return 'reference'
  if (role === 'guide') return 'wiki'
  return 'work'
}

function formatFrontmatter(fm: Frontmatter): string {
  const lines = [
    `title: "${fm.title}"`,
    `role: ${fm.role}`,
    `work_type: ${fm.work_type}`,
    `format: ${fm.format}`,
    `domain: ${fm.domain}`,
    `tags: [${fm.tags.join(', ')}]`,
    `audience: [${fm.audience.join(', ')}]`,
    `complexity: ${fm.complexity}`,
    `summary: >`,
    `  ${fm.summary}`,
    `curated_at: ${fm.curated_at}`,
    `curator: ${fm.curator}`,
    `source: ${fm.source}`,
  ]

  if (fm.author) lines.push(`author: "${fm.author}"`)
  if (fm.origin_date) lines.push(`origin_date: "${fm.origin_date}"`)
  if (fm.era) lines.push(`era: ${fm.era}`)
  if (fm.tradition) lines.push(`tradition: ${fm.tradition}`)
  if (fm.related_docs?.length) lines.push(`related_docs: [${fm.related_docs.join(', ')}]`)
  if (fm.parent_work) lines.push(`parent_work: "${fm.parent_work}"`)

  return lines.join('\n')
}

function parseFrontmatterYaml(yaml: string, fallback: Frontmatter): Frontmatter {
  try {
    // Wrap in frontmatter delimiters so gray-matter can parse it
    const wrapped = `---\n${yaml}\n---\n`
    const { data } = matter(wrapped)

    const result: Frontmatter = {
      title: data.title || fallback.title,
      role: ROLES.includes(data.role) ? data.role : fallback.role,
      work_type: WORK_TYPES.includes(data.work_type) ? data.work_type : fallback.work_type,
      format: FORMATS.includes(data.format) ? data.format : fallback.format,
      domain: DOMAINS.includes(data.domain) ? data.domain : fallback.domain,
      tags: Array.isArray(data.tags) ? data.tags.map(String) : fallback.tags,
      audience: Array.isArray(data.audience) ? data.audience.map(String) : fallback.audience,
      complexity: COMPLEXITIES.includes(data.complexity) ? data.complexity : fallback.complexity,
      summary: data.summary || fallback.summary,
      curated_at: data.curated_at || fallback.curated_at,
      curator: data.curator || fallback.curator,
      source: data.source || fallback.source,
    }

    // Optional enriched fields
    if (data.author) result.author = data.author
    if (data.origin_date) result.origin_date = String(data.origin_date)
    if (data.era && ERAS.includes(data.era)) result.era = data.era
    if (data.tradition) result.tradition = data.tradition
    if (Array.isArray(data.related_docs)) result.related_docs = data.related_docs.map(String)
    if (data.parent_work) result.parent_work = String(data.parent_work)

    return result
  } catch {
    console.log('⚠️  Could not parse edited YAML — using previous values.')
    return fallback
  }
}

// ─── Cross-Reference Suggestions ────────────────────────────────────────────

type RelatedDocSuggestion = {
  /** Docs to add to the new document's related_docs */
  forNew: string[]
  /** Existing docs that should add the new document to their related_docs */
  bidirectional: { path: string; title: string }[]
  /** Whether this document would be an island (zero connections) */
  isIsland: boolean
}

/**
 * Score and suggest related documents based on tag overlap, domain match, and audience overlap.
 * Returns suggestions for the new document AND bidirectional suggestions for existing docs.
 */
export function suggestRelatedDocs(
  newFrontmatter: Frontmatter,
  newRelativePath: string,
): RelatedDocSuggestion {
  const corpus = scanCorpus()

  if (corpus.length === 0) {
    return { forNew: [], bidirectional: [], isIsland: true }
  }

  const scored: { entry: CorpusEntry; score: number }[] = []

  for (const entry of corpus) {
    // Don't suggest self
    if (entry.relativePath === newRelativePath) continue

    const fm = entry.frontmatter
    let score = 0

    // Shared tags (2x each)
    const existingTags = new Set(fm.tags || [])
    for (const tag of newFrontmatter.tags || []) {
      if (existingTags.has(tag)) score += 2
    }

    // Same domain (1x)
    if (fm.domain === newFrontmatter.domain) score += 1

    // Audience overlap (0.5x each)
    const existingAudience = new Set(fm.audience || [])
    for (const aud of newFrontmatter.audience || []) {
      if (existingAudience.has(aud)) score += 0.5
    }

    // Same tradition (1x)
    if (fm.tradition && newFrontmatter.tradition && fm.tradition === newFrontmatter.tradition) score += 1

    // Same era (0.5x)
    if (fm.era && newFrontmatter.era && fm.era === newFrontmatter.era) score += 0.5

    if (score > 0) {
      scored.push({ entry, score })
    }
  }

  // Sort by score descending, take top 5
  scored.sort((a, b) => b.score - a.score)
  const top = scored.slice(0, 5)

  const forNew = top.map((s) => s.entry.relativePath)
  const bidirectional = top
    .filter((s) => s.score >= 2) // Only suggest bidirectional for strong matches
    .map((s) => ({
      path: s.entry.relativePath,
      title: (s.entry.frontmatter.title as string) || s.entry.relativePath,
    }))

  return {
    forNew,
    bidirectional,
    isIsland: forNew.length === 0,
  }
}
