/**
 * Constellation Graph Generator (Phase 1.6 prep)
 *
 * Emits the hierarchical knowledge-graph node set for `@opencosmos/constellation`:
 *   tradition  → synthesized from `tradition` (fallback `domain`) per source work
 *   work       → every doc in knowledge/sources/ with work_type: 'work'
 *   section    → every H2 heading inside a work
 *   quote      → every embeddable quote in knowledge/quotes/*.yaml
 *
 * Edges:
 *   tradition → work     type: 'hierarchy'
 *   work      → section  type: 'contains'
 *   quote     → work     type: 'cites'        (when source_work resolves to a known work)
 *   quote     → tradition type: 'member_of'   (fallback when source_work is null)
 *
 * After topology is built, ForceAtlas2 settles positions. The result is written
 * to Upstash Redis under two keys:
 *   knowledge:constellation         — full graph, gzip-compressed, Base64-encoded
 *   knowledge:constellation:preview — top 40 nodes by degree, < 5KB
 *
 * The legacy wiki graph (knowledge:graph) is generated by generate-wiki-graph.ts
 * and is unchanged — the sigma renderer at /knowledge/graph keeps working until
 * the constellation package replaces it in Phase 1.6 proper.
 *
 * Usage: pnpm graph:constellation
 */

import { readFileSync, existsSync, readdirSync, statSync } from 'node:fs'
import { resolve, dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { gzipSync } from 'node:zlib'
import matter from 'gray-matter'
import Graph from 'graphology'
import forceAtlas2 from 'graphology-layout-forceatlas2'
import { Redis } from '@upstash/redis'
import { Index } from '@upstash/vector'
import {
  parseYamlFile,
  COLLECTIVE_BUCKETS,
  EMBEDDABLE_STATUSES,
  type JsonlRecord,
} from '../normalize-quotes/shared.js'
import {
  TRADITION_TO_DOMAIN,
  TRADITION_TO_PARENT_TRADITION,
  UMBRELLA_TRADITIONS,
  resolveDomainForTradition,
} from './tradition-domain.js'

// ─── Path setup + .env loading ────────────────────────────────────────────────

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT_DIR = resolve(__dirname, '..', '..')
const KNOWLEDGE_DIR = resolve(ROOT_DIR, 'knowledge')
const SOURCES_DIR = resolve(KNOWLEDGE_DIR, 'sources')
const QUOTES_DIR = resolve(KNOWLEDGE_DIR, 'quotes')
const WIKI_DIR = resolve(KNOWLEDGE_DIR, 'wiki')
// Wiki subdirs that contribute synthesis-tier bridge nodes. Each file in
// these dirs has a `synthesizes: string[]` frontmatter listing the source
// paths (relative to knowledge/) that the wiki node weaves together.
const WIKI_SUBDIRS = ['entities', 'concepts', 'connections'] as const

function loadEnv(envPath: string) {
  if (!existsSync(envPath)) return
  for (const line of readFileSync(envPath, 'utf-8').split('\n')) {
    const match = line.match(/^\s*([^#=]+?)\s*=\s*"?(.+?)"?\s*$/)
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2]
  }
}

loadEnv(join(ROOT_DIR, 'apps', 'web', '.env'))
loadEnv(join(ROOT_DIR, 'apps', 'web', '.env.local'))

// ─── Types ────────────────────────────────────────────────────────────────────

type Tier = 'domain' | 'tradition' | 'work' | 'section' | 'quote' | 'synthesis'
type EdgeType =
  | 'hierarchy'    // tradition → work
  | 'contains'     // work → section
  | 'cites'        // quote → work | section
  | 'member_of'    // quote → tradition (fallback)
  | 'synthesizes'  // synthesis → work
  | 'semantic'     // work ↔ work — top-K cosine-similarity neighbor

interface ConstellationNode {
  id:        string
  tier:      Tier
  label:     string
  domain?:   string         // work/section: copied from work frontmatter
  tradition?: string        // tradition slug this node belongs to
  author?:   string         // work/quote
  parent?:   string         // section: parent work id; quote: source work id (if any)
  category?: string         // quote: taxonomic tag
  provenanceStatus?: string // quote: verified | attributed | …
  // Layout-computed
  degree:    number
  x:         number
  y:         number
}

interface ConstellationLink {
  source: string
  target: string
  type:   EdgeType
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function slugify(text: string): string {
  return text
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
}

function titleCase(slug: string): string {
  // Split on both `-` and whitespace so raw labels like `psychological realism`
  // (literal space) Title-Case correctly to "Psychological Realism", not just
  // "Psychological realism" (which the dash-only split would produce).
  return slug
    .split(/[-\s]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ')
}

// ─── Work + section scan ─────────────────────────────────────────────────────

interface ScannedWork {
  workNode:        ConstellationNode
  sectionNodes:    ConstellationNode[]
  traditionLabel:  string   // raw tradition string from frontmatter, before slugifying
}

interface ScannedQuote {
  node:            ConstellationNode
  traditionLabel:  string   // raw tradition string for tradition node label preservation
}

/** Extract H2 headings from the body of a source doc. */
function extractH2Sections(body: string): string[] {
  const sections: string[] = []
  for (const line of body.split('\n')) {
    const m = line.match(/^## (.+)$/)
    if (m) sections.push(m[1].trim())
  }
  return sections
}

function scanWorks(): ScannedWork[] {
  if (!existsSync(SOURCES_DIR)) return []
  const works: ScannedWork[] = []

  for (const file of readdirSync(SOURCES_DIR)) {
    if (!file.endsWith('.md')) continue
    const fullPath = resolve(SOURCES_DIR, file)
    if (!statSync(fullPath).isFile()) continue

    const raw = readFileSync(fullPath, 'utf-8')
    let fm: Record<string, unknown> = {}
    let body = ''
    try {
      const parsed = matter(raw)
      fm = parsed.data as Record<string, unknown>
      body = parsed.content
    } catch (err) {
      console.warn(`  ⚠️  Skipping ${file} — frontmatter parse error: ${(err as Error).message.split('\n')[0]}`)
      continue
    }

    const workType = String(fm.work_type ?? 'work')
    if (workType !== 'work') continue   // skip collections/references for now

    const relPath = relative(ROOT_DIR, fullPath)
    const id = `sources/${file.replace(/\.md$/, '')}`
    const title = String(fm.title ?? file.replace(/\.md$/, '').replace(/-/g, ' '))
    // Tradition is now mandatory in source frontmatter; emit a warning if missing.
    // Domain is derived via the shared tradition→domain config — no longer
    // read from the source file's `domain:` field (which has been retired).
    if (typeof fm.tradition !== 'string' || !fm.tradition) {
      console.warn(`  ⚠️  ${file} has no tradition: field — node will land in domain/uncategorized`)
    }
    const traditionRaw = (typeof fm.tradition === 'string' && fm.tradition) ? String(fm.tradition) : 'uncategorized'
    const tradition = slugify(traditionRaw)
    const domain = resolveDomainForTradition(tradition)
    const author = typeof fm.author === 'string' ? fm.author : undefined

    const workNode: ConstellationNode = {
      id,
      tier:      'work',
      label:     title,
      domain,
      tradition,
      author,
      degree:    0,
      x:         0,
      y:         0,
    }

    // H2 sections — slug per-file with indexed disambiguation on collision.
    // Note: this does not yet match the content-hash IDs emitted by
    // embed-knowledge.ts when slugs collide. Phase 1.7 (semantic edges) will
    // sync them. For visualization, indexed slugs are sufficient.
    const headings = extractH2Sections(body)
    const slugCount = new Map<string, number>()
    const sectionNodes: ConstellationNode[] = []
    for (const heading of headings) {
      const baseSlug = slugify(heading) || 'section'
      const seenBefore = slugCount.get(baseSlug) ?? 0
      slugCount.set(baseSlug, seenBefore + 1)
      const slug = seenBefore === 0 ? baseSlug : `${baseSlug}-${seenBefore + 1}`
      sectionNodes.push({
        id:       `${relPath}#${slug}`,
        tier:     'section',
        label:    heading,
        domain,
        tradition,
        parent:   id,
        degree:   0,
        x:        0,
        y:        0,
      })
    }

    works.push({ workNode, sectionNodes, traditionLabel: traditionRaw })
  }

  return works
}

// ─── Quote scan ──────────────────────────────────────────────────────────────

function scanQuotes(workIds: Set<string>): ScannedQuote[] {
  if (!existsSync(QUOTES_DIR)) return []
  const out: ScannedQuote[] = []

  for (const file of readdirSync(QUOTES_DIR)) {
    if (!file.endsWith('.yaml')) continue
    const fullPath = resolve(QUOTES_DIR, file)
    if (!statSync(fullPath).isFile()) continue

    const bucket = file.replace(/\.yaml$/, '')
    let parsed
    try {
      parsed = parseYamlFile(fullPath, bucket)
    } catch (err) {
      console.warn(`  ⚠️  Skipping ${file} — yaml parse failed: ${(err as Error).message.split('\n')[0]}`)
      continue
    }

    const relPath = relative(ROOT_DIR, fullPath)

    for (const record of parsed.records) {
      const status = record.provenance?.status
      if (!status || !EMBEDDABLE_STATUSES.has(status)) continue

      const sourceWork = typeof record.source_work === 'string' ? record.source_work : null
      const parent = sourceWork && workIds.has(sourceWork) ? sourceWork : undefined

      const traditionRaw = pickQuoteTradition(record, parsed.isCollective, bucket)
      const tradition = slugify(traditionRaw)

      out.push({
        node: {
          id:                `${relPath}#${record.id}`,
          tier:              'quote',
          label:             truncateLabel(record.text),
          author:            record.author,
          tradition,
          parent,
          category:          record.category,
          provenanceStatus:  status,
          degree:            0,
          x:                 0,
          y:                 0,
        },
        traditionLabel: traditionRaw,
      })
    }
  }

  return out
}

function pickQuoteTradition(record: JsonlRecord, isCollective: boolean, bucket: string): string {
  // Prefer the per-quote synthesized tradition; fall back to the collective bucket
  // (proverbs / attributed-collectives / anonymous) so those records still cluster.
  const recTradition = (record as { tradition?: unknown }).tradition
  if (typeof recTradition === 'string' && recTradition) return recTradition
  if (isCollective && COLLECTIVE_BUCKETS.has(bucket)) return bucket
  return 'uncategorized'
}

function truncateLabel(text: string, max = 80): string {
  const flat = text.replace(/\s+/g, ' ').trim()
  return flat.length > max ? flat.slice(0, max - 1) + '…' : flat
}

// ─── Wiki bridge scan ────────────────────────────────────────────────────────

interface ScannedWikiNode {
  node:           ConstellationNode
  /** Resolved work IDs that this synthesis node references. Already filtered
   *  to only those work IDs that exist in the corpus (broken refs dropped). */
  synthesizesWorkIds: string[]
}

/**
 * Walk knowledge/wiki/{entities,concepts,connections}/*.md and build a
 * synthesis-tier node per file. Each one carries a list of work IDs it
 * weaves together — those become `synthesizes`-type edges in `buildEdges`.
 *
 * Wiki frontmatter convention (set by /standardize-knowledge):
 *   role: wiki
 *   synthesizes:
 *     - sources/buddhism-the-dhammapada.md
 *     - sources/literature-leaves-of-grass.md
 *
 * The `.md` suffix is stripped on the way in so refs match the work-tier
 * `id` shape (`sources/{basename}` without extension).
 */
function scanWiki(workIds: Set<string>): ScannedWikiNode[] {
  if (!existsSync(WIKI_DIR)) return []
  const out: ScannedWikiNode[] = []

  for (const subdir of WIKI_SUBDIRS) {
    const dirPath = resolve(WIKI_DIR, subdir)
    if (!existsSync(dirPath)) continue

    for (const file of readdirSync(dirPath)) {
      if (!file.endsWith('.md')) continue
      // Skip meta files
      if (file === 'index.md' || file === 'log.md' || file === 'README.md') continue
      const fullPath = resolve(dirPath, file)
      if (!statSync(fullPath).isFile()) continue

      const raw = readFileSync(fullPath, 'utf-8')
      let fm: Record<string, unknown> = {}
      try {
        const parsed = matter(raw)
        fm = parsed.data as Record<string, unknown>
      } catch (err) {
        console.warn(`  ⚠️  Skipping wiki/${subdir}/${file} — frontmatter parse error: ${(err as Error).message.split('\n')[0]}`)
        continue
      }

      const basename = file.replace(/\.md$/, '')
      const id = `wiki/${subdir}/${basename}`
      const title = String(fm.title ?? basename.replace(/-/g, ' '))
      const domain = typeof fm.domain === 'string' ? fm.domain : 'cross'

      // Resolve and dedupe synthesized work refs.
      const rawSynth = Array.isArray(fm.synthesizes) ? fm.synthesizes : []
      const resolved = new Set<string>()
      for (const ref of rawSynth) {
        if (typeof ref !== 'string') continue
        // Strip `.md` and any leading `knowledge/` prefix; the work-tier id is
        // `sources/{basename}` without extension.
        const normalized = ref
          .trim()
          .replace(/^knowledge\//, '')
          .replace(/\.md$/, '')
        if (workIds.has(normalized)) resolved.add(normalized)
      }

      // Skip wiki nodes that don't bridge anything in the current corpus —
      // they'd be orphan dots rather than connective tissue.
      if (resolved.size === 0) continue

      out.push({
        node: {
          id,
          tier:   'synthesis',
          label:  title,
          domain,
          degree: 0,
          x:      0,
          y:      0,
        },
        synthesizesWorkIds: Array.from(resolved),
      })
    }
  }

  return out
}

// ─── Semantic edges (Upstash Vector) ─────────────────────────────────────────

interface SemanticEdge {
  source: string
  target: string
  weight: number   // sum of cosine-similarity scores across aggregated chunks
}

/**
 * For each work, query Upstash Vector with the work's identity (title + author)
 * and aggregate the top matches by source path to discover its semantic
 * neighbors. Emits at most `topK` undirected edges per work, dedupes pairs
 * across the corpus.
 *
 * Cost: one query per work (~84 queries × ~150 ms ≈ 12–15 s for our corpus).
 * Skips silently if env vars aren't set or the index doesn't exist yet.
 */
async function computeSemanticEdges(
  works:   ScannedWork[],
  topK:    number,
  perWorkSampleSize: number,
): Promise<SemanticEdge[]> {
  const url   = process.env.UPSTASH_VECTOR_REST_URL
  const token = process.env.UPSTASH_VECTOR_REST_TOKEN
  if (!url || !token) {
    console.warn('  ⚠️  UPSTASH_VECTOR_REST_URL/TOKEN not set — skipping semantic-edge pass.')
    return []
  }

  const index = new Index({ url, token })
  const edges = new Map<string, SemanticEdge>()  // unordered pair key → best weight seen

  for (const w of works) {
    const queryText = [w.workNode.label, w.workNode.author].filter(Boolean).join(' ')
    if (!queryText) continue

    let matches: Array<{ id: string; score: number; metadata?: Record<string, unknown> }>
    try {
      matches = await index.query({
        data: queryText,
        topK: perWorkSampleSize,
        includeMetadata: true,
      })
    } catch (err) {
      console.warn(`  ⚠️  Vector query failed for ${w.workNode.id}: ${(err as Error).message.split('\n')[0]}`)
      continue
    }

    // Aggregate by neighbor work id (sum of similarity scores across all of
    // this neighbor's chunks that landed in the top-K). Self matches dropped.
    //
    // The Upstash chunk metadata stores `source` as the path relative to the
    // repo root (e.g. `knowledge/sources/foo.md`), while work-tier ids are
    // `sources/foo` (no `knowledge/` prefix, no `.md` suffix). Normalize both
    // edges of the comparison.
    const neighborScore = new Map<string, number>()
    for (const m of matches) {
      const sourcePath = String(m.metadata?.source ?? '')
      if (!sourcePath) continue
      const targetWorkId = sourcePath
        .replace(/^knowledge\//, '')
        .replace(/\.md$/, '')
      if (targetWorkId === w.workNode.id) continue
      // Only link works → works for now (skip wiki/quote/etc. neighbors).
      if (!targetWorkId.startsWith('sources/')) continue
      neighborScore.set(targetWorkId, (neighborScore.get(targetWorkId) ?? 0) + m.score)
    }

    const top = [...neighborScore.entries()]
      .sort(([, a], [, b]) => b - a)
      .slice(0, topK)

    for (const [targetWorkId, weight] of top) {
      const key = [w.workNode.id, targetWorkId].sort().join('|')
      const existing = edges.get(key)
      if (!existing || existing.weight < weight) {
        edges.set(key, { source: w.workNode.id, target: targetWorkId, weight })
      }
    }
  }

  return [...edges.values()]
}

// ─── Tradition + domain synthesis ────────────────────────────────────────────

function synthesizeTraditions(
  works: ScannedWork[],
  quotes: ScannedQuote[],
): ConstellationNode[] {
  // Track the first display label seen for each slug so casing from the source
  // frontmatter is preserved when present, while collapsing onto URL-safe slugs.
  const labelBySlug = new Map<string, string>()

  const visit = (raw: string | undefined) => {
    if (!raw) return
    const slug = slugify(raw)
    if (!slug) return
    // Suppress the catch-all 'uncategorized' bucket so it doesn't appear as a
    // visible tradition node. Its quotes lose their member_of edge but stay
    // in the graph; better than emitting a weird "Uncategorized" anchor.
    if (slug === 'uncategorized') return
    if (!labelBySlug.has(slug)) labelBySlug.set(slug, raw)
  }

  for (const w of works) visit(w.traditionLabel)
  for (const q of quotes) visit(q.traditionLabel)

  // Include umbrella traditions (e.g. `philosophy`) that have no work directly
  // tagged with them — they exist purely as nesting categorizers.
  for (const u of UMBRELLA_TRADITIONS) {
    if (!labelBySlug.has(u)) labelBySlug.set(u, u)
  }

  return [...labelBySlug.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([slug, raw]) => ({
      id:        `tradition/${slug}`,
      tier:      'tradition' as Tier,
      label:     /^[a-z]/.test(raw) ? titleCase(raw) : raw,
      tradition: slug,
      degree:    0,
      x:         0,
      y:         0,
    }))
}

/**
 * Emit one node per top-level domain reachable from the corpus's traditions.
 * Domains are derived from the `tradition-domain.ts` config (no frontmatter
 * dependency). The returned set is sorted alphabetically for stable output.
 */
function synthesizeDomains(
  traditionNodes: ConstellationNode[],
): ConstellationNode[] {
  const domains = new Set<string>()
  for (const t of traditionNodes) {
    if (!t.tradition) continue
    const d = resolveDomainForTradition(t.tradition)
    domains.add(d)
  }
  // Always include the umbrella traditions' canonical domains too, even if
  // their slug somehow isn't in the tradition set yet.
  for (const u of UMBRELLA_TRADITIONS) {
    domains.add(resolveDomainForTradition(u))
  }

  return [...domains]
    .sort()
    .map((slug) => ({
      id:        `domain/${slug}`,
      tier:      'domain' as Tier,
      label:     titleCase(slug),
      domain:    slug,
      degree:    0,
      x:         0,
      y:         0,
    }))
}

// ─── Edge building ───────────────────────────────────────────────────────────

function buildEdges(
  domains:    ConstellationNode[],
  traditions: ConstellationNode[],
  works:      ScannedWork[],
  quotes:     ConstellationNode[],     // already-flattened quote nodes
  wiki:       ScannedWikiNode[],
): ConstellationLink[] {
  const edges: ConstellationLink[] = []
  const traditionIds = new Set(traditions.map((t) => t.id))
  const domainIds    = new Set(domains.map((d) => d.id))

  // domain → tradition (or domain → umbrella tradition → child tradition).
  //
  // Each tradition slug routes to ONE parent: either an umbrella tradition
  // listed in TRADITION_TO_PARENT_TRADITION (e.g. stoicism → philosophy), or
  // directly to the domain via TRADITION_TO_DOMAIN. Umbrella traditions
  // themselves get a domain edge from TRADITION_TO_DOMAIN[umbrella] (so
  // wisdom → philosophy). ForceAtlas2 pulls Stoicism toward Philosophy and
  // Philosophy toward Wisdom — the cluster forms via chained edges.
  for (const t of traditions) {
    if (!t.tradition) continue
    const slug = t.tradition

    const parentSlug = TRADITION_TO_PARENT_TRADITION[slug]
    if (parentSlug) {
      const parentId = `tradition/${parentSlug}`
      if (traditionIds.has(parentId)) {
        edges.push({ source: parentId, target: t.id, type: 'hierarchy' })
        continue
      }
    }

    // No umbrella parent — link directly to a domain.
    const domainSlug = TRADITION_TO_DOMAIN[slug] ?? 'uncategorized'
    const domainId = `domain/${domainSlug}`
    if (domainIds.has(domainId)) {
      edges.push({ source: domainId, target: t.id, type: 'hierarchy' })
    }
  }

  // tradition → work
  for (const w of works) {
    const tid = `tradition/${w.workNode.tradition}`
    if (traditionIds.has(tid)) {
      edges.push({ source: tid, target: w.workNode.id, type: 'hierarchy' })
    }
  }

  // work → section
  for (const w of works) {
    for (const s of w.sectionNodes) {
      edges.push({ source: w.workNode.id, target: s.id, type: 'contains' })
    }
  }

  // quote → work (cites)  or  quote → tradition (member_of)
  for (const q of quotes) {
    if (q.parent) {
      edges.push({ source: q.id, target: q.parent, type: 'cites' })
    } else if (q.tradition) {
      const tid = `tradition/${q.tradition}`
      if (traditionIds.has(tid)) {
        edges.push({ source: q.id, target: tid, type: 'member_of' })
      }
    }
  }

  // synthesis → work (synthesizes) — the lateral bridges. A wiki concept like
  // "Impermanence" emits one edge per work it weaves together; ForceAtlas2
  // pulls the synthesis node toward the centroid of those works, creating the
  // visible cross-tradition connective tissue.
  for (const w of wiki) {
    for (const targetWorkId of w.synthesizesWorkIds) {
      edges.push({ source: w.node.id, target: targetWorkId, type: 'synthesizes' })
    }
  }

  return edges
}

// ─── Main ────────────────────────────────────────────────────────────────────

async function main() {
  console.log('📚 Scanning knowledge/sources/ …')
  const works = scanWorks()
  const workNodes = works.map((w) => w.workNode)
  const sectionNodes = works.flatMap((w) => w.sectionNodes)
  console.log(`  ${workNodes.length} works · ${sectionNodes.length} sections`)

  const workIdSet = new Set(workNodes.map((w) => w.id))

  console.log('💬 Scanning knowledge/quotes/ …')
  const scannedQuotes = scanQuotes(workIdSet)
  const quoteNodes = scannedQuotes.map((q) => q.node)
  console.log(`  ${quoteNodes.length} embeddable quotes`)

  console.log('🪢 Scanning knowledge/wiki/ for synthesis bridges …')
  const wikiNodes = scanWiki(workIdSet)
  const wikiBridgeCount = wikiNodes.reduce((acc, w) => acc + w.synthesizesWorkIds.length, 0)
  console.log(`  ${wikiNodes.length} synthesis nodes spanning ${wikiBridgeCount} work refs`)

  const traditionNodes = synthesizeTraditions(works, scannedQuotes)
  console.log(`✨ Synthesized ${traditionNodes.length} traditions`)

  const domainNodes = synthesizeDomains(traditionNodes)
  console.log(`🌍 Synthesized ${domainNodes.length} domains: ${domainNodes.map((d) => d.label).join(', ')}`)

  const allNodes: ConstellationNode[] = [
    ...domainNodes,
    ...traditionNodes,
    ...workNodes,
    ...sectionNodes,
    ...quoteNodes,
    ...wikiNodes.map((w) => w.node),
  ]

  console.log('🔗 Building structural edges …')
  const edges = buildEdges(domainNodes, traditionNodes, works, quoteNodes, wikiNodes)
  console.log(`  ${edges.length} structural edges (hierarchy + contains + cites + member_of + synthesizes)`)

  // Optional semantic-edge pass — adds work↔work cosine-similarity bridges as a
  // softer underlayer beneath the curated wiki bridges. Skipped via --no-semantic
  // (e.g. local dev without Upstash creds).
  const args = new Set(process.argv.slice(2))
  if (!args.has('--no-semantic')) {
    console.log('🌌 Computing semantic edges via Upstash Vector …')
    const semanticEdges = await computeSemanticEdges(works, /* topK per work */ 3, /* sample size */ 30)
    console.log(`  ${semanticEdges.length} semantic edges`)
    for (const e of semanticEdges) {
      edges.push({ source: e.source, target: e.target, type: 'semantic' })
    }
  } else {
    console.log('⏭  --no-semantic: skipping semantic-edge pass')
  }

  // ─── Build graphology instance for layout ─────────────────────────────────
  const graph = new Graph({ type: 'undirected' })
  for (const node of allNodes) {
    graph.addNode(node.id, { x: node.x, y: node.y, ...node })
  }
  for (const edge of edges) {
    try {
      graph.addEdge(edge.source, edge.target, { type: edge.type })
    } catch {
      // Ignore duplicates or missing nodes
    }
  }

  const nodeMap = new Map(allNodes.map((n) => [n.id, n]))
  graph.forEachNode((id) => {
    const node = nodeMap.get(id)
    if (node) node.degree = graph.degree(id)
  })

  // ─── Seed positions from existing Redis state if available ────────────────
  let existingPositions = new Map<string, { x: number; y: number }>()
  let redis: Redis | null = null

  try {
    redis = new Redis({
      url:   process.env.UPSTASH_VECTOR_URL ?? process.env.UPSTASH_REDIS_REST_URL ?? '',
      token: process.env.UPSTASH_VECTOR_TOKEN ?? process.env.UPSTASH_REDIS_REST_TOKEN ?? '',
    })

    const existing = await redis.get<string>('knowledge:constellation')
    if (existing) {
      const { gunzipSync } = await import('node:zlib')
      const json    = gunzipSync(Buffer.from(existing, 'base64')).toString()
      const payload = JSON.parse(json) as { nodes: Array<{ id: string; x: number; y: number }> }
      existingPositions = new Map(payload.nodes.map((n) => [n.id, { x: n.x, y: n.y }]))
      console.log(`  Seeded ${existingPositions.size} positions from prior run`)
    }
  } catch (err) {
    console.warn('  Redis not available — running layout from scratch:', (err as Error).message)
  }

  // Initialize positions: prior position if known, else neighbor centroid + jitter
  graph.forEachNode((id) => {
    const pos = existingPositions.get(id)
    if (pos) {
      graph.setNodeAttribute(id, 'x', pos.x)
      graph.setNodeAttribute(id, 'y', pos.y)
      return
    }
    const neighbors = graph.neighbors(id)
    const cx = neighbors.reduce((s, n) => s + (existingPositions.get(n)?.x ?? 0), 0) / (neighbors.length || 1)
    const cy = neighbors.reduce((s, n) => s + (existingPositions.get(n)?.y ?? 0), 0) / (neighbors.length || 1)
    graph.setNodeAttribute(id, 'x', cx + (Math.random() - 0.5) * 10)
    graph.setNodeAttribute(id, 'y', cy + (Math.random() - 0.5) * 10)
  })

  console.log(`⚡ Running ForceAtlas2 on ${allNodes.length} nodes / ${edges.length} edges …`)
  forceAtlas2.assign(graph, {
    iterations: 100,
    settings: {
      strongGravityMode: true,
      gravity:           0.05,
      barnesHutOptimize: true,
      scalingRatio:      2,
      slowDown:          10,
    },
  })

  graph.forEachNode((id, attrs) => {
    const node = nodeMap.get(id)
    if (!node) return
    node.x = attrs.x as number
    node.y = attrs.y as number
  })

  // ─── Output payload ───────────────────────────────────────────────────────
  const outputNodes = allNodes.map((n) => ({
    id:               n.id,
    tier:             n.tier,
    label:            n.label,
    domain:           n.domain,
    tradition:        n.tradition,
    author:           n.author,
    parent:           n.parent,
    category:         n.category,
    provenanceStatus: n.provenanceStatus,
    degree:           n.degree,
    x:                n.x,
    y:                n.y,
  }))

  const outputLinks = edges.map((e) => ({ source: e.source, target: e.target, type: e.type }))
  const generatedAt = Date.now()
  const fullPayload = JSON.stringify({ nodes: outputNodes, links: outputLinks, generatedAt })

  // ─── Summary or persist ───────────────────────────────────────────────────
  const summary: Record<Tier, number> = {
    domain:    domainNodes.length,
    tradition: traditionNodes.length,
    work:      workNodes.length,
    section:   sectionNodes.length,
    quote:     quoteNodes.length,
    synthesis: wikiNodes.length,
  }
  console.log(`📊 Tier counts: ${Object.entries(summary).map(([t, n]) => `${t}=${n}`).join('  ')}`)

  if (!redis) {
    console.log('⚠️  No Redis — printing summary only (set UPSTASH_REDIS_REST_URL + UPSTASH_REDIS_REST_TOKEN to persist)')
    console.log(`  Total: ${outputNodes.length} nodes · ${outputLinks.length} edges`)
    return
  }

  console.log('💾 Writing to Redis …')
  const compressed = gzipSync(Buffer.from(fullPayload)).toString('base64')
  await redis.set('knowledge:constellation', compressed)

  // Preview key — top 40 nodes by degree, stripped fields, < 5KB
  const previewNodes = [...outputNodes]
    .sort((a, b) => b.degree - a.degree)
    .slice(0, 40)
    .map(({ id, x, y, degree, tier, tradition }) => ({ id, x, y, degree, tier, tradition }))

  await redis.set('knowledge:constellation:preview', JSON.stringify({ nodes: previewNodes, generatedAt }))

  console.log(`✅ Done — ${outputNodes.length} nodes, ${outputLinks.length} edges`)
  console.log(`  Full payload: ${(compressed.length / 1024).toFixed(1)} KB (Base64+gzip)`)
}

main().catch((err) => {
  console.error('Constellation generator failed:', err)
  process.exit(1)
})
