/**
 * knowledge/iching/**.md  →  apps/web/lib/iching-data.ts
 *
 * The markdown frontmatter is the source of truth; this file is generated.
 * Same arrangement as the taoteching glossary, where entries are hand-written
 * and terms.yaml is built from them.
 *
 * It is generated into the app rather than read from disk at runtime because
 * the cast happens on the client, and lib/knowledge.ts's fs-from-cwd pattern is
 * server-only. Sixty-four rows is a rounding error in the bundle.
 *
 *   pnpm xenso:build-iching
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { load } from 'js-yaml'

const KNOWLEDGE = resolve(__dirname, '..', '..', 'knowledge', 'iching')
const OUT = resolve(__dirname, '..', '..', 'apps', 'web', 'lib', 'iching-data.ts')

type Row = Record<string, unknown>

/**
 * Frontmatter only. js-yaml rather than gray-matter deliberately: gray-matter is
 * an apps/web dependency, not a root one, and adding a root dep regenerates the
 * shared lockfile — which has silently broken sibling apps' builds here before.
 */
function frontmatter(text: string): Row {
  const m = /^---\r?\n([\s\S]*?)\r?\n---/.exec(text)
  if (!m) throw new Error('no frontmatter')
  return (load(m[1]) ?? {}) as Row
}

function read(dir: string): Row[] {
  const path = join(KNOWLEDGE, dir)
  return readdirSync(path)
    .filter(f => f.endsWith('.md'))
    .sort()
    .map(f => {
      try {
        return frontmatter(readFileSync(join(path, f), 'utf8'))
      } catch (e) {
        throw new Error(`${dir}/${f}: ${(e as Error).message}`)
      }
    })
}

const hexagrams = read('hexagrams')
const trigrams = read('trigrams')

if (hexagrams.length !== 64) throw new Error(`expected 64 hexagrams, found ${hexagrams.length}`)
if (trigrams.length !== 8) throw new Error(`expected 8 trigrams, found ${trigrams.length}`)

// Order by King Wen number rather than trusting filename sort.
hexagrams.sort((a, b) => Number(a.number) - Number(b.number))
hexagrams.forEach((h, i) => {
  if (Number(h.number) !== i + 1) throw new Error(`hexagram ${i + 1} is numbered ${h.number}`)
  if (!/^[01]{6}$/.test(String(h.lines))) throw new Error(`hexagram ${h.number}: bad figure "${h.lines}"`)
})

const q = (v: unknown) => (v == null || v === '' ? 'null' : JSON.stringify(String(v)))

const hexRows = hexagrams
  .map(h => {
    const t = h.trigrams as { lower: string; upper: string }
    return `  { number: ${h.number}, chinese: ${JSON.stringify(h.chinese)}, pinyin: ${JSON.stringify(h.pinyin)}, figure: ${JSON.stringify(h.lines)}, trigrams: { lower: ${JSON.stringify(t.lower)}, upper: ${JSON.stringify(t.upper)} }, render: ${q(h.render)}, status: ${JSON.stringify(h.status)}, judgment: ${q(h.judgment)} },`
  })
  .join('\n')

const triRows = trigrams
  .map(
    t =>
      `  { id: ${JSON.stringify(t.id)}, chinese: ${JSON.stringify(t.chinese)}, pinyin: ${JSON.stringify(t.pinyin)}, figure: ${JSON.stringify(t.lines)}, imageChinese: ${JSON.stringify(t.image_chinese)}, render: ${q(t.render)}, status: ${JSON.stringify(t.status)} },`,
  )
  .join('\n')

const lookup = hexagrams.map(h => `  ${JSON.stringify(String(h.lines))}: ${h.number},`).join('\n')

const drafts = hexagrams.filter(h => h.status === 'draft').length

writeFileSync(
  OUT,
  `// GENERATED by scripts/xenso/build-iching.ts — do not edit.
// Source of truth: knowledge/iching/hexagrams/*.md and knowledge/iching/trigrams/*.md
// Renderings still undrafted: ${drafts} of 64.

export type Hexagram = {
  number: number
  chinese: string
  pinyin: string
  /** Bottom → top, '1' = yang. */
  figure: string
  trigrams: { lower: string; upper: string }
  /** The single word a player sees. Null until the rendering is drafted. */
  render: string | null
  status: string
  judgment: string | null
}

export type Trigram = {
  id: string
  chinese: string
  pinyin: string
  figure: string
  imageChinese: string
  render: string | null
  status: string
}

/** Indexed by King Wen number minus one. */
export const HEXAGRAMS: readonly Hexagram[] = [
${hexRows}
]

export const TRIGRAMS: readonly Trigram[] = [
${triRows}
]

/** Figure string (bottom → top) → King Wen number. */
export const HEXAGRAM_BY_FIGURE: Readonly<Record<string, number>> = {
${lookup}
}
`,
  'utf8',
)

console.log(`wrote ${OUT}`)
console.log(`  64 hexagrams, 8 trigrams — ${drafts} renderings still undrafted`)
